name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-12', 'ubuntu-22.04']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Build
        run: go build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: adjust-excel-cell-width
          retention-days: 5 